"""injector.py — register every historical constructor into Telethon's runtime.

Telethon does NOT build its TL classes on the fly: ``telethon_generator`` turns a
``.tl`` schema into ``.py`` files *at package-build time*, so at runtime Telethon
only knows the constructors of the layer it was generated against. Anything older
(``userContact``, ``userForeign``, the old ``userProfilePhoto``, ``fileLocation``,
``peerNotifySettingsEmpty``, ...) simply has no class, so ``tgread_object()`` hits
an unknown id and raises ``TypeNotFoundError``.

This module fills that gap. It reads the full historical schema
(``AndroidTelePorter.compat.tl_reader._REGISTRY``, built from ``data/legacy.tl``)
and, for every id Telethon does NOT already know, synthesizes a lightweight class
with a ``from_reader`` and registers it into Telethon's global ``tlobjects`` dict.

After :func:`inject`, native ``BinaryReader.tgread_object()`` can decode a user
blob end to end: modern ids resolve to Telethon's real classes, legacy ids to our
synthesized ones, and the whole recursion is driven by Telethon itself.

Registration is additive (``setdefault`` semantics): we never overwrite a class
Telethon already ships, so the rest of the library keeps using real Telethon
objects for serialization.

Provenance / how to compare with Telethon
-----------------------------------------
Nothing here is a verbatim copy of a single Telethon file. Instead it is a
generic, data-driven re-implementation of the per-constructor code that
Telethon's build-time generator EMITS. Each block below cites the exact
Telethon-1 source it mirrors so you can diff the behaviour:

* field reading  -> telethon_generator/generators/tlobject.py::_write_arg_read_code
                    (the function that generates every class' ``from_reader`` body)
* scalar readers -> telethon/extensions/binaryreader.py (read_int/read_long/...)
* bool / vector  -> telethon/extensions/binaryreader.py::tgread_bool / tgread_object
* object shape   -> telethon/tl/tlobject.py::TLObject (CONSTRUCTOR_ID, from_reader)
"""

from telethon.tl.tlobject import TLObject
from telethon.extensions import BinaryReader

from AndroidTelePorter.compat.tl_reader import _REGISTRY, _SCALARS, _Constructor, _Arg
from AndroidTelePorter.models.userconfig import UserConfig


class _LegacyBase(TLObject):
    """Base class for every synthesized legacy constructor.

    Inherits directly from ``telethon/tl/tlobject.py::TLObject`` so that
    ``isinstance(obj, TLObject)`` is True and Telethon utilities such as
    ``TLObject.pretty_format`` work correctly.

    Each concrete subclass is created dynamically in :func:`_make_class` with
    a class-level ``_NAME`` (clean predicate, e.g. ``'userEmpty'``) and the
    usual ``CONSTRUCTOR_ID`` / ``SUBCLASS_OF_ID`` / ``from_reader`` that
    ``BinaryReader.tgread_object()`` needs.

    Decoded field values are stored per-instance in ``_values`` (a plain dict)
    and exposed as attributes via ``__getattr__``.

    ``_bytes()`` raises ``NotImplementedError`` — these are read-only historical
    objects that appear inside Android user blobs we decode but never re-serialize.
    """

    _NAME: str = ''   # set per subclass by _make_class

    def __getattr__(self, item):
        # __getattr__ fires only when normal attribute lookup fails (not in __dict__).
        try:
            return self.__dict__['_values'][item]
        except KeyError:
            raise AttributeError(item)

    def to_dict(self) -> dict:
        return {'_': type(self)._NAME, **self.__dict__.get('_values', {})}

    def _bytes(self):
        raise NotImplementedError(
            f'{type(self)._NAME} is a legacy read-only constructor; '
            'serialization back to bytes is not implemented.'
        )

    def __repr__(self) -> str:
        body = ', '.join(f'{k}={v!r}' for k, v in self.__dict__.get('_values', {}).items())
        return f'{type(self)._NAME}({body})'


def _read_single(reader: BinaryReader, arg: _Arg):
    # Equivalent to the non-vector branches generated by
    # telethon_generator/generators/tlobject.py::_write_arg_read_code (lines ~580-639):
    #   scalar  -> reader.read_*/tgread_* (see _SCALARS in tl_reader)   (gen 580-615)
    #   object  -> reader.tgread_object()                                (gen 617-620)
    #   true    -> True (flag-only field, nothing on the wire)           (gen 607-609)
    if arg.kind == 'scalar':
        return _SCALARS[arg.scalar](reader)
    if arg.kind == 'object':
        return reader.tgread_object()      # native Telethon recursion
    if arg.kind == 'bool':
        # Telethon generates `reader.tgread_bool()` for Bool fields — see
        # telethon/extensions/binaryreader.py::tgread_bool (lines 117-132).
        return reader.tgread_bool()
    if arg.kind == 'true':
        return True
    return reader.tgread_object()


def _read_value(reader: BinaryReader, arg: _Arg):
    # Vector branch of _write_arg_read_code (gen lines 562-573): read the boxed
    # vector constructor id (0x1cb5c415), then a count, then that many items.
    if not arg.is_vector:
        return _read_single(reader, arg)
    reader.read_int(signed=False)          # boxed vector id (0x1cb5c415)
    count = reader.read_int()
    return [_read_single(reader, arg) for _ in range(count)]


def _make_class(ctor: _Constructor):
    """Synthesize a concrete subclass of :class:`_LegacyBase` for one constructor."""

    def from_reader(cls, reader: BinaryReader):
        # Generic equivalent of the body Telethon's generator writes per class in
        # telethon_generator/generators/tlobject.py::_write_from_reader /
        # _write_arg_read_code. tgread_object() has already consumed the 4-byte id.
        flags: dict = {}
        obj = cls.__new__(cls)   # skip __init__; _LegacyBase has none to call
        obj._values = {}
        for arg in ctor.args:
            if arg.flag_indicator:
                # flag word: generator does `flags = reader.read_int()` (gen 575-577).
                # (Telethon reads it signed; the bit tests below are identical.)
                flags[arg.name] = reader.read_int(signed=False)
                obj._values[arg.name] = flags[arg.name]
                continue
            if arg.flag is not None:
                # Optional field gated by a flag bit (gen 549-560).
                present = bool(flags.get(arg.flag, 0) & (1 << arg.flag_bit))
                if arg.kind == 'true':
                    # `name = bool(flags & bit)` — nothing read (gen 552-555).
                    obj._values[arg.name] = present
                    continue
                if not present:
                    obj._values[arg.name] = None
                    continue
            obj._values[arg.name] = _read_value(reader, arg)
        return obj

    return type(
        f'{ctor.name}_{ctor.id:08x}',
        (_LegacyBase,),
        {
            # Class-level attributes required by BinaryReader.tgread_object()
            # (telethon/tl/tlobject.py::TLObject lines 34-36 + from_reader 208-210)
            # and by _LegacyBase.to_dict() / __repr__.
            '_NAME': ctor.name,
            'CONSTRUCTOR_ID': ctor.id,
            'SUBCLASS_OF_ID': 0,
            'from_reader': classmethod(from_reader),
        },
    )


_injected = False


def inject() -> int:
    """Register every missing historical constructor into Telethon's registry.

    Idempotent and additive: existing Telethon classes are left untouched.

    Returns:
        int: how many constructors were newly registered.
    """
    global _injected
    # Mutate the very dict BinaryReader.tgread_object() looks up.
    from telethon.tl import alltlobjects
    registry = alltlobjects.tlobjects

    added = 0
    for cid, ctor in _REGISTRY.items():
        if cid in registry:
            continue
        registry[cid] = _make_class(ctor)
        added += 1

    _injected = True
    return added


def read_user(data: bytes):
    """Decode a user blob using Telethon's native ``tgread_object``.

    Ensures the historical constructors are injected first, then lets Telethon
    drive the whole recursive decode. Returns the raw decoded object (a real
    Telethon class for modern ids, a :class:`TLObjectProxy` for legacy ones) —
    handy for debugging an unknown blob. Most callers want
    :func:`read_user_config`.
    """
    if not _injected:
        inject()
    return BinaryReader(bytes(data)).tgread_object()


def read_user_config(data: bytes) -> UserConfig:
    """Decode a user blob into a :class:`UserConfig` DTO.

    Decodes natively via :func:`read_user`, then keeps only the handful of
    fields the converters care about (id / first_name / username / phone / bot).
    ``is_empty`` is True for the ``userEmpty`` placeholder constructor. Works for
    both real Telethon objects and :class:`TLObjectProxy` instances because both
    expose ``to_dict()``.

    Raises:
        TypeNotFoundError: a constructor id (root or nested) is not present in
            ``data/legacy.tl`` and is unknown to Telethon.
    """
    tree = read_user(data).to_dict()
    return UserConfig(
        id=tree.get('id'),
        first_name=tree.get('first_name'),
        username=tree.get('username'),
        phone=tree.get('phone'),
        bot=bool(tree.get('bot')),
        is_empty=str(tree.get('_', '')).lower() == 'userempty',
    )
